### ISSUE TITLE
Cannot install on Arch / Manjaro 18

### ISSUE THREAD

**Issue by JoshMcCullough** [fresc81/node-curses#10]
>$ npm i --save curses
>
> curses@0.0.10 install /home/josh/Projects/teslagov/multi-git/node_modules/curses
> node ./pre-build.js
>
>/home/josh/Projects/teslagov/multi-git/node_modules/curses/pre-build.js:26
>,       tarExtract = tar.Extract(path.resolve(__dirname, 'deps'))
>
>TypeError: tar.Extract is not a function
>    at Object.<anonymous> (/home/josh/Projects/teslagov/multi-git/node_modules/curses/pre-build.js:26:20)
>    at Module._compile (internal/modules/cjs/loader.js:734:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
>    at Module.load (internal/modules/cjs/loader.js:626:32)
>    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
>    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
>    at executeUserCode (internal/bootstrap/node.js:526:15)
>    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

**Comment by samratrocks** [comment]
Will probably be fixed by [this PR.](https://github.com/fresc81/node-curses/pull/9)

**Comment by JoshMcCullough** [comment]
Looks promising! Nice.
