### ISSUE TITLE
Install from npm fails

### ISSUE THREAD

**Issue by lucaspiller** [fresc81/node-curses#2]
``` shell
$ npm install curses
npm http GET https://registry.npmjs.org/curses
npm http 304 https://registry.npmjs.org/curses
npm http GET https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/graceful-fs

> curses@0.0.10 install /Users/luca/code/1gam/march/node_modules/curses
> node ./pre-build.js


url.js:96
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Object.urlParse [as parse] (url.js:96:11)
    at Object.<anonymous> (/Users/luca/code/1gam/march/node_modules/curses/pre-build.js:19:34)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! curses@0.0.10 install: `node ./pre-build.js`
npm ERR! `sh "-c" "node ./pre-build.js"` failed with 1
npm ERR!
npm ERR! Failed at the curses@0.0.10 install script.
npm ERR! This is most likely a problem with the curses package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./pre-build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls curses
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "/usr/local/Cellar/node/0.8.21/bin/node" "/usr/local/bin/npm" "install" "curses"
npm ERR! cwd /Users/luca/code/1gam/march
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/luca/code/1gam/march/npm-debug.log
npm ERR! not ok code 0
```

Additional `npm-debug.log` file here:

https://gist.github.com/lucaspiller/5085352

**Comment by fresc81** [comment]
it seems that the correct download url for your system is not listed in "/source-urls.json". it uses node's "os.platform()" function to get the correct ncurses version for your system. you could add an entry for your system and use the url for ncurses like linux, mac and solaris do.
please reply me if a custom system string worked for you, then i will add it for next release
