### ISSUE TITLE
Post-install fails.

### ISSUE THREAD

**Issue by brainkim** [fresc81/node-curses#5]
Tried to install via npm. `node-gyp rebuild --release` doesn't work for some reason. Would love to help but I'm not too familiar with node-gyp/curses to begin with. I'm using:  
- gcc: 4.7.2
- node-gyp: 0.10.9
- make: GNU 3.81
- node: 0.10

Probably just something dumb on my end,
Brian

```
> curses@0.0.10 postinstall /home/brian/Projects/github/curses
> node-gyp rebuild --release

make: Entering directory `/home/brian/Projects/github/curses/build'
  CXX(target) Release/obj.target/curses/src/curses.o
In file included from ../src/curses.cc:18:0:
../src/ptrwrap.h: In static member function ‘static v8::Handle<v8::Value> PtrWrap<T>::ToString(const v8::Arguments&)’:
../src/ptrwrap.h:132:22: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
../src/ptrwrap.h:132:22: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/ptrwrap.h: In instantiation of ‘static v8::Handle<v8::Value> PtrWrap<T>::ToString(const v8::Arguments&) [with T = _win_st]’:
../src/ptrwrap.h:66:3:   required from ‘static v8::Persistent<v8::Function> PtrWrap<T>::Init(const char*) [with T = _win_st]’
../src/curses.cc:60:1:   required from here
../src/ptrwrap.h:132:3: error: ‘memset’ was not declared in this scope
../src/ptrwrap.h: In instantiation of ‘static v8::Handle<v8::Value> PtrWrap<T>::ToString(const v8::Arguments&) [with T = screen]’:
../src/ptrwrap.h:66:3:   required from ‘static v8::Persistent<v8::Function> PtrWrap<T>::Init(const char*) [with T = screen]’
../src/curses.cc:61:1:   required from here
../src/ptrwrap.h:132:3: error: ‘memset’ was not declared in this scope
make: *** [Release/obj.target/curses/src/curses.o] Error 1
make: Leaving directory `/home/brian/Projects/github/curses/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Linux 3.5.0-17-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/brian/Projects/github/curses
gyp ERR! node -v v0.10.5
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! curses@0.0.10 postinstall: `node-gyp rebuild --release`
npm ERR! `sh "-c" "node-gyp rebuild --release"` failed with 1
npm ERR! 
npm ERR! Failed at the curses@0.0.10 postinstall script.
npm ERR! This is most likely a problem with the curses package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls curses
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.5.0-17-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "."
npm ERR! cwd /home/brian/Projects/github/curses
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/brian/Projects/github/curses/npm-debug.log
npm ERR! not ok code 0
```

**Comment by fresc81** [comment]
see #6
